# TO TEST THE READ LENGTH I 'READ' 2 random FASTQ files and measured their length using this 'script'.

# 70258_LV_1
s = "GGCTGGGGCAGCGCCTTGGCCGAGACCAGTTTCTCCACGTCTTTGTAGCAGTAGACATGGGGGCCGTGGACGATGT"
print(len(s))

# 704490_LV_2
s2 = "GTTGCTTTATGCGATGACTTCCAGGAAGATGAACAGAAGTTTTGGGGAAAATACCTATATGAAATTGCCAGAAGAC"
print(len(s2))


# one of r1 from PORK02
s3 = "GGACCATTATCCTGCGCTTTGCTATTCAGGACATTTCAGTCGAAGAAACCTCTGCCAAAGAAGGTCTGCTGCTTTG"
print(len(s3))


""" PORK 08 """
# H2LFWBBXY_4_170UDI-idt-UMI_1.fastq -> In 'PORK_08.xls' it is marked as length: 101
s4 = "CGCAAACACGAGAGAAGAGTAAAGGAACTCACTTACCAAACTGAGGAAGACCGCAAGAACATTCTCAGGCTCCAGG"
print("Length H2LFWBBXY_4_170UDI-idt-UMI_1.fastq:", len(s4))

# H2LFWBBXY_6_198UDI-idt-UMI_2.fastq -> In 'PORK_08.xls' it is marked as length: 101
# Read @K00310:245:H2LFWBBXY:6:1101:11789:1314
s5 = "CCTGCTCTGTGGCGGCCATTTTTTCACGGATCTTCCCGATCTCGGTGCTCACCCCAGTGGTGGCCACGATGCCTAT"
print("Length H2LFWBBXY_6_198UDI-idt-UMI_2.fastq:", len(s5))

# H2LFWBBXY_7_187UDI-idt-UMI_1.fastq -> In 'PORK_08.xls' it is marked as length: 101
# Read @K00310:245:H2LFWBBXY:7:1101:5741:1314
s6 = "CCTTTCAGTCTTAAAAGTTCCTGTTTCTGGAGTTTTCTTCCCACTTCTAGGGATGATTTCCACCATTTTTGCACCT"
print("Length H2LFWBBXY_7_187UDI-idt-UMI_1.fastq:", len(s6))

