---
title: "isoforms_venn_BC1_PI.LV"
author: "FLC"
date: '2022-06-08'
output: html_document
---
```{r}
library(ggplot2)
library(ggVennDiagram)
library(stringr)
```



```{r setup, include=FALSE}
# Loading of the results from DESeq2
DESeq2_BC1_PI.LV <- read.csv("/home/fllobet/Documents/RNA-Seq_TFM/BC1_PI.LV/ISOFORMS/BC1_PI.iF.LV.SF.Results_a_0.05.csv", sep = ";")

# |FC| > 1.5 filtering
DESeq2_BC1_PI.LV <- DESeq2_BC1_PI.LV[which(DESeq2_BC1_PI.LV[,3] >= log2(1.5) | DESeq2_BC1_PI.LV[,3] <= -log2(1.5)),]

# FDR < 0.05 filtering 
DESeq2_BC1_PI.LV <- DESeq2_BC1_PI.LV[which(DESeq2_BC1_PI.LV[,7] < 0.05),]

# Loading of the results from EBSeq
EBSeq_BC1_PI.LV <- read.csv("/home/fllobet/Documents/RNA-Seq_TFM/BC1_PI.LV/ISOFORMS/EBSeq/BC1_PI.iF.LV_EBrb.Results05.csv", sep = ";", row.names = 1)

# |FC| > 1.5 filtering
EBSeq_BC1_PI.LV <-  EBSeq_BC1_PI.LV[which(EBSeq_BC1_PI.LV[,5] >= log2(1.5) | EBSeq_BC1_PI.LV[,5] <= -log2(1.5)),]

# PP DE > 0.95 filtering 
EBSeq_BC1_PI.LV <- EBSeq_BC1_PI.LV[which(EBSeq_BC1_PI.LV[,7] > 0.95),]
```

```{r}
# INSPIRATION: https://stackoverflow.com/questions/70228591/set-the-color-of-categories-in-venn-diagram-in-r

# Division of the 'feature' column of the DESeq2 data into 2 columns 
DESeq2_BC1_PI.LV <- cbind(DESeq2_BC1_PI.LV[,1], DESeq2_BC1_PI.LV)
DESeq2_BC1_PI.LV[,1:2] <- str_split_fixed(DESeq2_BC1_PI.LV[,1],"_", n = 2) 

# Creating a list cotaining the lists of ID's
sets_of_DEI <- list(DESeq2 = DESeq2_BC1_PI.LV$`DESeq2_BC1_PI.LV[, 1]`, EBSeq = EBSeq_BC1_PI.LV$ENSEMBL.ID)

venn <- Venn(sets_of_DEI)
data <- process_data(venn)

vn <- ggplot() + 
  # 1. Circles layer
  geom_sf(aes(fill = count), data = venn_region(data)) +
  # 2. Labels of the circles layer
  geom_sf_text(aes(label = name, color = name), data = venn_setlabel(data), fontface = "bold", size = 6, nudge_y = 0.4) +
  # 3. Numbers inside of the circles
  geom_sf_text(aes(label = count), data = venn_region(data), size = 10, fontface = "bold", color = "#FFFFFF") +
  # User-defined fill colors of the circles
  scale_fill_steps(low = "#bdb76b", high = "#2f847c") +
  # User-defined color of the labels
  scale_color_manual(values = c("#37867c", "#8ea373")) + 
  
  # Removla of the 'count' gradinet scale + change of the name pch character
  guides(color = "none",
         fill = "none") +
   # White background
  theme_void() + 
  # Setting all the fonts to Ubuntu
  theme(text = element_text(family = "Ubuntu"),
        legend.key = element_blank()) 
 
saveRDS(vn, "~/Documents/RNA-Seq_TFM/Extra_figures/venn/BC1_PI.LV.rds")


```

