# TO TEST THE READ LENGTH I 'READ' 2 random FASTQ files and measured their length using this 'script'.

# 70258_LV_1
s = "GGCTGGGGCAGCGCCTTGGCCGAGACCAGTTTCTCCACGTCTTTGTAGCAGTAGACATGGGGGCCGTGGACGATGT"
print(len(s))

# 704490_LV_2
s2 = "GTTGCTTTATGCGATGACTTCCAGGAAGATGAACAGAAGTTTTGGGGAAAATACCTATATGAAATTGCCAGAAGAC"
print(len(s2))
